---
title: "Extra credit"
subtitle: "INFO 2950 - Spring 2023"
author: "Lina Liu"
date: "05/10/23"
format: pdf
editor: visual
---

## Setup

Load packages and data:

```{r}
#| label: load-packages

library(tidyverse)
library(usmap)
library(ggplot2)
library(wesanderson)
library(scales)

#| label: load-data
childcare_costs <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-05-09/childcare_costs.csv')
counties <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-05-09/counties.csv')
```

## Extra credit

**Research Question:** What is the labor force participation of mothers who have children throughout the United States in the year 2018? How does this compare to 2008?

```{r}
#| label: data-wrangling
labor_part_2018 <- childcare_costs |>
  # select relevant columns to use for analysis
  select(county_fips_code, study_year, flfpr_20to64_under6, flfpr_20to64_6to17) |>
  # filter so we only use the year 2018
  filter(study_year == "2018") |>
  # did this justttt in case if there's n/a values
  drop_na() |>
  # combine the column for labor participation of mothers with children under the age
  # of 6 alongside the labor participation of mothers with children 6 to 17.
  pivot_longer(
    cols = -c("county_fips_code", "study_year"),
    names_transform = parse_number,
    values_to = "pct"
  ) |>
  # get rid of the name column, which is kindaaa unnecessary :p
  select(-name) |>
  # because there's two rows of the same area (one for the labor participation
  # percentage of mothers with children under 6 age group and the other one for
  # the 6-17 age group), I decided to average them together to get the total
  # labor participation
  group_by(county_fips_code) |>
  summarize(pct = mean(pct)) |>
  # aligning the fips code of the data so it matches w/ the fips code and column
  # name that the usmap package gave. I added a leading zero in the beginning &
  # changed the column name to fips
  mutate(
    county_fips_code = as.character(county_fips_code),
    fips = if_else(nchar(county_fips_code) == 4,
                               paste0("0", county_fips_code),
                               county_fips_code),
    pct = pct/100)
```

```{r}
#| label: creating-visualization
#| fig-height: 10
#| fig-width: 12

# I followed this tutorial for the US map:
# https://jtr13.github.io/cc19/different-ways-of-plotting-u-s-map-in-r.html

plot_usmap(data = labor_part_2018,
           values = "pct",
           linewidth = 0.0005)  + 
  labs(title = "Labor Force Participation of Mothers throughout the United States",
       subtitle = "Separated by county for the year 2018",
       caption = "Source: National Database of Childcare Prices",
       fill = "Labor Force Participation") + 
  theme(panel.background = element_blank(),
        legend.position = "left") +
  scale_fill_gradientn(colours = wes_palette("Zissou1", 100,
                                             type = "continuous"),
                       labels = percent)
```
